site_name: pysb-pkpd

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
              options:
                  docstring_style: numpy
              paths: [src]  # search packages in the src folder

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - User Guide:
    - PK/PD Macros: macros.md
    - Standard Model Generators: standard.md
    - How-To Guides: how-to-guides.md
    - Tutorials: tutorials.md
    - API Reference: reference.md
  - About:
    - License: license.md
    - Contributing: contributing.md
    - Citing: citing.md
    - Supporting: supporting.md
    - Source Code: https://github.com/blakeaw/pysb-pkpd
  - Resources:
      - What is PK/PD Modeling: pkpd-modeling.md
      - Related Software: related-software.md
  - Contact/Support: contact-support.md
